In [7]:

import numpy as np
from proj1_helpers import *
from least_squares import *

In [3]:
y, tx, ids = load_csv_data('Data/train.csv')
txTest, ids = load_csv_Test('Data/test.csv')

In [9]:

mse, testW  = least_squares(y,tx)
print(mse)
yPred = predict_labels(testW, txTest)
print(yPred)




hej
0.3396868094771245
[-1. -1. -1. ... -1.  1. -1.]


In [7]:
t = tx.T @ tx
print(t.shape)
print(y @ tx)

(30, 30)
[ 2.69166238e+07 -6.82104965e+06 -6.52243855e+06 -1.64623481e+06
  7.10049113e+07  7.72387010e+07  7.09120913e+07 -1.84407245e+05
 -1.56895267e+06 -8.25581500e+06 -1.52260008e+05  8.70636890e+04
  7.09873190e+07 -1.79386969e+06  5.91454000e+02 -1.25523000e+03
 -3.83784984e+06  1.98971900e+03 -1.64694300e+03 -3.10636210e+06
  4.01074000e+03 -1.24358072e+07 -4.60520000e+04  4.73342420e+07
  4.88802491e+07  4.88803806e+07  7.04906523e+07  7.09822138e+07
  7.09811341e+07 -2.62409515e+06]


[[ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 [ 154.916   10.418   94.714 ... -999.    -999.      30.638]
 ...
 [-999.      78.256   79.699 ... -999.    -999.      78.984]
 [ 133.457   77.54    88.989 ... -999.    -999.      70.969]
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]]


array([[ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
       [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
       [ 154.916,   10.418,   94.714, ..., -999.   , -999.   ,   30.638],
       ...,
       [-999.   ,   78.256,   79.699, ..., -999.   , -999.   ,   78.984],
       [ 133.457,   77.54 ,   88.989, ..., -999.   , -999.   ,   70.969],
       [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992]])