In [1]:
import importlib
import numpy as np
from proj1_helpers import *
from least_squares import *
from ridge_regression import *
import gradient_descent

In [2]:
y, tx, ids = load_csv_data('Data/train.csv')
txTest, idsTest = load_csv_Test('Data/test.csv')

In [4]:

mse, testW  = least_squares(y,tx)




In [5]:
mse, testW = ridge_regression(y,tx,0.005)
print(mse)

l = testW

0.3398074969310615


In [14]:

importlib.reload(gradient_descent)
mse, testW = gradient_descent.gradient_descent(y, tx, l, 50, 1)

0.679614993862123
0.6796010180820145
401606410.3560941
1.320218191300933e+22
4.3416586459229066e+35
1.4277963641470835e+49
4.695446242536534e+62
1.5441428464001735e+76
5.078062886738599e+89
1.669970025233617e+103
5.4918577169686866e+116
1.8060504516665984e+130
5.939371342208647e+143
1.9532196295013247e+157
6.42335139740665e+170
2.1123811450277036e+184
6.946769413347206e+197
2.2845122148438496e+211
7.512839061194705e+224
2.4706696857504387e+238
8.125035883725516e+251
2.671996523556957e+265
8.787118634394032e+278
2.88972883063966e+292
9.503152355249748e+305
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf


c:\Users\sebas\Documents\GitHub\ML_EPFL\Project_1\gradient_descent.py:10: RuntimeWarning: overflow encountered in matmul
  


inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
nan
nan
nan


c:\Users\sebas\Documents\GitHub\ML_EPFL\Project_1\gradient_descent.py:12: RuntimeWarning: overflow encountered in matmul
  print(loss)
c:\Users\sebas\Documents\GitHub\ML_EPFL\Project_1\gradient_descent.py:8: RuntimeWarning: invalid value encountered in matmul
  for n_iter in range(max_iters):


In [7]:

yPred = predict_labels(testW, txTest)
print(yPred)
create_csv_submission(idsTest, yPred, "testSub.csv")

(30, 30)
[ 2.69166238e+07 -6.82104965e+06 -6.52243855e+06 -1.64623481e+06
  7.10049113e+07  7.72387010e+07  7.09120913e+07 -1.84407245e+05
 -1.56895267e+06 -8.25581500e+06 -1.52260008e+05  8.70636890e+04
  7.09873190e+07 -1.79386969e+06  5.91454000e+02 -1.25523000e+03
 -3.83784984e+06  1.98971900e+03 -1.64694300e+03 -3.10636210e+06
  4.01074000e+03 -1.24358072e+07 -4.60520000e+04  4.73342420e+07
  4.88802491e+07  4.88803806e+07  7.04906523e+07  7.09822138e+07
  7.09811341e+07 -2.62409515e+06]


[[ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 [ 154.916   10.418   94.714 ... -999.    -999.      30.638]
 ...
 [-999.      78.256   79.699 ... -999.    -999.      78.984]
 [ 133.457   77.54    88.989 ... -999.    -999.      70.969]
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]]


array([[ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
       [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
       [ 154.916,   10.418,   94.714, ..., -999.   , -999.   ,   30.638],
       ...,
       [-999.   ,   78.256,   79.699, ..., -999.   , -999.   ,   78.984],
       [ 133.457,   77.54 ,   88.989, ..., -999.   , -999.   ,   70.969],
       [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992]])